apt install -y mtr
apt install -y ss
apt install -y tree
apt install -y last
apt install -y pstree
apt install -y htop
apt install -y history
apt install -y stat
apt install -y pv
apt install -y mount
apt install -y column
apt install -y file
apt install -y id
apt install -y at
apt install -y du
apt install -y look
apt install -y factor
apt install -y tac
apt install -y disown
apt install -y convert
apt install -y host
apt install -y dig
apt install -y host
apt install -y dstat
apt install -y nc
apt install -y pdftk

