yum install -y mtr
yum install -y ss
yum install -y tree
yum install -y last
yum install -y pstree
yum install -y htop
yum install -y history
yum install -y stat
yum install -y pv
yum install -y mount
yum install -y column
yum install -y file
yum install -y id
yum install -y at
yum install -y du
yum install -y look
yum install -y factor
yum install -y tac
yum install -y disown
yum install -y convert
yum install -y host
yum install -y dig
yum install -y host
yum install -y dstat
yum install -y nc
yum install -y pdftk
# detail see : https://www.aliyun.com/jiaocheng/197767.html
